AssetTrackingSystem/Controllers/OrganizationBranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetTrackingSystem.Context;
using AssetTrackingSystem.Models.ViewModel;

namespace AssetTrackingSystem.Controllers
{
    public class OrganizationBranchController:Controller
    {
        AssetTrackingSystemDBContext db = new AssetTrackingSystemDBContext();
        public ActionResult Create()
        {

            var organizationBranch = db.OrganizationBranches.SingleOrDefault(m => m.Id == 1);


            var organizationSelectListItems = GetOrganizationSelectListItems();

            var organizationBranchVM = new OrganizationBranchCreateVM();

          


            organizationBranchVM.OrganizationList = organizationSelectListItems;


            return View(organizationBranchVM);
        }

        private List<SelectListItem> GetOrganizationSelectListItems()
        {
            var organizations = db.Organizations.ToList();
            List<SelectListItem> organizationSelectListItems = new List<SelectListItem>();
            organizationSelectListItems.Add(new SelectListItem() {Value = "", Text = "Select..."});

            foreach (var organization in organizations)
            {
                organizationSelectListItems.Add(new SelectListItem()
                {
                    Value = organization.Id.ToString(),
                    Text = organization.Name
                });
            }
            return organizationSelectListItems;
        }

        [HttpPost]
        public ActionResult Create(OrganizationBranchCreateVM organizationBranchCreateVm)
        {
            var organizationBranch = organizationBranchCreateVm.OrganizationBranch;

            db.OrganizationBranches.Add(organizationBranch);

            int rowAffected = db.SaveChanges();

            organizationBranchCreateVm.OrganizationList = GetOrganizationSelectListItems();

            return View(organizationBranchCreateVm);
        }



    }
}

AssetTrackingSystem/Views/OrganizationBranch/Create.cshtml
@model AssetTrackingSystem.Models.ViewModel.OrganizationBranchCreateVM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .alert {
        width: 46.5%;
        margin: auto auto 5px auto;
    }
</style>



<div class="container">
    <div class="form_my_style">
        @if (ViewBag.Message != null)
        {
            <div class="alert alert-success" id="success-alert">
                <button type="button" class="close" data-dismiss="alert">x</button>
                <strong>Success! </strong>
                Branch have added to your list.
            </div>
        }
        @using (Html.BeginForm("Create", "OrganizationBranch", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            <h2>Branch Setup</h2>

            <div class="form-group">
                <label for="country" class="col-sm-4 control-label">Organization</label>
                <div class="col-sm-8">

                    @Html.DropDownListFor(m => m.OrganizationBranch.OrganizationId, new SelectList(Model.OrganizationList, "Value", "Text"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.OrganizationBranch.OrganizationId)
                </div>
            </div>
            <!-- /.form-group -->

            <div class="form-group">
                @Html.LabelFor(m => m.OrganizationBranch.Name, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.OrganizationBranch.Name, new { @placeholder = "Branch Name", @class = "form-control", autofocus = true })
                    @*<span class="help-block">Last Name, First Name, eg.: Smith, Harry</span>*@
                    @Html.ValidationMessageFor(m => m.OrganizationBranch.Name, null, new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.OrganizationBranch.ShortName, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.OrganizationBranch.ShortName, new { @placeholder = "Short Name", @class = "form-control", autofocus = true })
                    @*<span class="help-block">Last Name, First Name, eg.: Smith, Harry</span>*@
                    @Html.ValidationMessageFor(m => m.OrganizationBranch.ShortName, null, new { @class = "text-danger" })
                </div>
            </div>




            <div class="form-group">
                <div class="col-sm-8 col-sm-offset-4">
                    <button type="submit" class="btn btn-primary btn-block">Save</button>
                </div>
            </div>
        }
    </div>


</div> <!-- ./container -->