AssetTrackingSystem/Controllers/SubCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssetTracking.BLL.Organization;
using AssetTracking.Model.Models.ViewModel;
using AssetTrackingSystemApps.Models;

namespace AssetTrackingSystemApps.Controllers
{
    public class SubCategoryController : Controller
    {
        //
        // GET: /SubCategory/


        private BaseCategoryManager _baseCategoryManager;

        public SubCategoryController()
        {
            _baseCategoryManager = new BaseCategoryManager();
        }

        public ActionResult Create()
        {

            SubCategoryCreateVM modelVM = new SubCategoryCreateVM();

            var generalCategories = _baseCategoryManager.GetAllGeneralCategories();

            List<SelectListItem> generalCategoriesSelectListItems = new List<SelectListItem>()
            {
                new SelectListItem(){Value = "",Text = "Select..."}
            };

            foreach (var generalCategory in generalCategories)
            {
                SelectListItem item=new SelectListItem(){Value=generalCategory.Id.ToString(), Text=generalCategory.Name};

                generalCategoriesSelectListItems.Add(item);
            }


            modelVM.GeneralCategories = generalCategoriesSelectListItems;

            return View(modelVM);
        }
        [HttpPost]
        public ActionResult Create(SubCategory subCategory)
        {
            ViewBag.Message = "Saved Successfully!";
            return View();
        }


        public JsonResult GetCategoriesByGeneralCategory(int generalCategoryId)
        {

            var categories = _baseCategoryManager
                .GetCategoriesByGeneralCategory(generalCategoryId)
                .Select(c=>new{Id=c.Id, Name=c.Name});

            return Json(categories,JsonRequestBehavior.AllowGet);
        }
	}
}

AssetTrackingSystem/Views/SubCategory/Create.cshtml
@model AssetTracking.Model.Models.ViewModel.SubCategoryCreateVM
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .alert {
        width: 46.5%;
        margin: auto auto 5px auto;
    }
</style>



<div class="container">
    <div class="form_my_style">
        @if (ViewBag.Message != null)
{
    <div class="alert alert-success" id="success-alert">
        <button type="button" class="close" data-dismiss="alert">x</button>
        <strong>Success! </strong>
        Sub Category have added to your list.
    </div>
}
        @using (Html.BeginForm("Create", "SubCategory", FormMethod.Post, new {@class = "form-horizontal", role = "form"}))
        {

            <h2>Sub Category Setup</h2>
            <div class="form-group">
                <label for="genarelCategory" class="col-sm-4 control-label">Genarel Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("GeneralCategoryId", new SelectList(Model.GeneralCategories,"Value","Text"), new { @class = "form-control" })
                </div>
            </div>
            <!-- /.form-group -->

            <div class="form-group">
                <label for="category" class="col-sm-4 control-label">Category</label>
                <div class="col-sm-8">
                    @Html.DropDownListFor(m=>m.SubCategory.CategoryId, Enumerable.Empty<SelectListItem>(), "--Select Category--", new {id="categoryId", @class = "form-control" })
                </div>
            </div>
            <!-- /.form-group -->
            <div class="form-group">
                @Html.LabelFor(m => m.SubCategory.Name, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.SubCategory.Name, new { @placeholder = "Sub Category/Brand", @class = "form-control", autofocus = true })
                    
                    @Html.ValidationMessageFor(m => m.SubCategory.Name, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.SubCategory.Code, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.SubCategory.Code, new { @placeholder = "Code", @class = "form-control", autofocus = true })
                    
                    @Html.ValidationMessageFor(m => m.SubCategory.Code, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.SubCategory.Description, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.SubCategory.Description, new { @placeholder = "Description", @class = "form-control", autofocus = true })
                    
                    @Html.ValidationMessageFor(m => m.SubCategory.Description, null, new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                <div class="col-sm-8 col-sm-offset-4">
                    <button type="submit" class="btn btn-primary btn-block">Save</button>
                </div>
            </div>
        }
    </div>

</div> <!-- ./container -->

}
@section scripts{
    <script>

        $("#GeneralCategoryId").change(function() {
            var generalCategoryId = $('#GeneralCategoryId').val();

            var jsonData = { generalCategoryId: generalCategoryId };

            $.ajax({
                url: "/SubCategory/GetCategoriesByGeneralCategory",
                data: JSON.stringify(jsonData),
                contentType: "application/json; charset=utf-8",
                success: function(data) {
                    // get json data list
                    $.each(data, function(key, category) {

                        var optionText = "<option value='" + category.Id + "'>" + category.Name + "</option>";
                        $('#categoryId').append(optionText);
                    });


                }


            });

        });

    </script>
}