AssetTrackingSystem/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using AssetTrackingSystem.BLL;
using AssetTrackingSystem.Context;
using AssetTrackingSystem.Models;
using AssetTrackingSystem.Models.ViewModel;
using AutoMapper;

namespace AssetTrackingSystem.Controllers
{
    public class OrganizationController : Controller
    {
        AssetTrackingSystemDBContext db = new AssetTrackingSystemDBContext();

        private OrganizationManager _organizationManager;

        public OrganizationController()
        {
            _organizationManager = new OrganizationManager();
        }
        public ActionResult Create()
        {
            var model = new OrganizationCreateVM();
            model.Organizations = db.Organizations.ToList();
            return View(model);
        }

        [HttpPost]
        public ViewResult Create(OrganizationCreateVM modelVM)
        {
            if (ModelState.IsValid)
            {
                Organization organization = Mapper.Map<Organization>(modelVM);
                bool isSaved = _organizationManager.Save(organization);

                if (isSaved)
                {
                    ViewBag.Message = "Saved Successfully!";
                }
            }
            
            return View(modelVM);
        }

        public ActionResult Search()
        {
            var organizations = GetAllOrganizations();
            return View(organizations);
        }

        [HttpPost]
        public ActionResult Search(OrganizationSearchCriteriaViewModel organizationSearchCriteria)
        {
            var organizations = GetOrganizationBySearchCriteria(organizationSearchCriteria);
            return View(organizations);
        }
        private List<Organization> GetAllOrganizations()
        {
            var organizations = db.Organizations.ToList();
            return organizations;

        }

        public List<Organization> GetOrganizationBySearchCriteria(OrganizationSearchCriteriaViewModel searchCriteriaViewModel)
        {
            var organizations = db.Organizations.AsQueryable();


            if (!String.IsNullOrEmpty(searchCriteriaViewModel.Name))
            {
                organizations = organizations.Where(c => c.Name.ToLower().Contains(searchCriteriaViewModel.Name.ToLower()));
            }

            if (!String.IsNullOrEmpty(searchCriteriaViewModel.Code))
            {
                organizations = organizations.Where(c => c.Code.Equals(searchCriteriaViewModel.Code));
            }

            if (!String.IsNullOrEmpty(searchCriteriaViewModel.Location))
            {
                organizations = organizations.Where(c => c.Location.ToLower().Contains(searchCriteriaViewModel.Location));
            }

            return organizations.OrderBy(o => o.Name).ToList();
        }

        [HttpPost]
        public ActionResult Edit(Organization organization)
        {
            //var existingOrganization = db.Organizations.SingleOrDefault(c => c.Id == organization.Id);


            //existingOrganization.Code = organization.Code;
            //existingOrganization.Name = organization.Name;
            //existingOrganization.Location = organization.Location;




            db.Organizations.Attach(organization);
            db.Entry(organization).State = EntityState.Modified;
            int rowAffected = db.SaveChanges();
            

            if (rowAffected>0)
            {
                ViewBag.Message = "Updated Successfully!";
            }
            return View(organization);
        }

        public ActionResult Edit(int? id)
        {
            if (id==null)
            {
                return HttpNotFound();
            }

            var existingOrganization = db.Organizations.SingleOrDefault(c => c.Id == id);

            if (existingOrganization == null)
            {
                return HttpNotFound();
            }
            return View(existingOrganization);
        }
    }
}

AssetTrackingSystem/Views/Organization/Edit.cshtml
@model AssetTrackingSystem.Models.Organization

@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container">

    <div class="form_my_style">
        <div class="alert alert-success">
            @if (ViewBag.Message != null)
            {
                <strong>@ViewBag.Message</strong>
            }

        </div>
        @using (Html.BeginForm("Edit", "Organization", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {

            <h2>Organization Edit</h2>
            @Html.ValidationSummary(true, "Please fill up the form!")
            @Html.HiddenFor(c=>c.Id)
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.EditorFor(m => m.Name, new { @placeholder = "Name", @class = "form-control", autofocus = true })
                    <span class="help-block">Last Name, First Name, eg.: Smith, Harry</span>
                    @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ShortName, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.ShortName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ShortName, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Code, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Code, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Location, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.Location, new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-8 col-sm-offset-4">
                    <button type="submit" class="btn btn-primary btn-block">Save</button>
                </div>
            </div>
        }
    </div>


</div> 

AssetTrackingSystem/Views/Organization/Search.cshtml
@using AssetTrackingSystem.Models
@model IEnumerable<AssetTrackingSystem.Models.Organization>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Search</title>
</head>
<body>
<div>
    <p>
        Search Result(s)
    </p>
    <p>
        <a href="@Url.Action("Create", "Organization")">Create</a>
    </p>

    <form action="Search" method="POST">
        <p>
            Name: <input type="text" name="Name" id="Name" />
        </p>
        <p>
            ShortName: <input type="text" name="ShortName" id="Code"/>
        </p>
        <p>
            Location: <input type="text" name="Location" id="Location" />
        </p>


        <p>
            <input type="submit" value="Show"/>
        </p>
    </form>
    @if (Model != null && Model.Any())
    {
        <table border="1">
            <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Code
                </th>
                <th>
                    Location
                </th>
            </tr>
            </thead>
            <tbody>
            @foreach (Organization organization in Model)
            {
                <tr>
                    <td>
                        @organization.Name
                    </td>
                    <td>
                        @organization.ShortName
                    </td>
                    <td>
                        @organization.Location
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit",new{id=organization.Id})
                    </td>
                </tr>
            }

            </tbody>

        </table>
    }
</div>
</body>
</html>

AssetTrackingSystem/Views/Organization/create.cshtml
@model AssetTrackingSystem.Models.ViewModel.OrganizationCreateVM
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">

    <div class="form_my_style">
        <div class="alert alert-success">
            @if (ViewBag.Message != null)
            {
                <strong>@ViewBag.Message</strong>
            }

        </div>
        @using (Html.BeginForm("Create", "Organization", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {

            <h2>Organization Setup</h2>
            @Html.ValidationSummary(true, "Please fill up the form!")
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.Name, new { @placeholder = "Name", @class = "form-control", autofocus = true })
                    <span class="help-block">Last Name, First Name, eg.: Smith, Harry</span>
                    @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ShortName, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.ShortName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ShortName, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Code, new { @class = "col-sm-4 control-label" })
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Code, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Location, new {@class = "col-sm-4 control-label"})
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.Location, new {@class = "form-control"})
                </div>
            </div>

    <table border="1">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    Code
                </th>
                <th>
                    Location
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var organization in Model.Organizations)
            {
                <tr>
                    <td>
                        @organization.Name
                    </td>
                    <td>
                        @organization.ShortName
                    </td>
                    <td>
                        @organization.Location
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = organization.Id })
                    </td>
                </tr>
            }

        </tbody>

    </table>

            <div class="form-group">
                <div class="col-sm-8 col-sm-offset-4">
                    <button type="submit" class="btn btn-primary btn-block">Save</button>
                </div>
            </div>
        }
    </div>


</div> <!-- ./container -->
@section scripts
{
    <script type="text/javascript" src="habijabi.js"></script>
}